### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/npm-gatsby-remark-copy-relative-linked-files#14]
Changed:

- Document HTML/JSX img tags, fix typos [#13](https://github.com/akabekobeko/npm-gatsby-remark-copy-relative-linked-files/pull/13) by [karlhorky](https://github.com/karlhorky)
- Support `<img />` tags in HTML and JSX [#12](https://github.com/akabekobeko/npm-gatsby-remark-copy-relative-linked-files/pull/12) by [karlhorky](https://github.com/karlhorky)

**Comment by karlhorky** [comment]
Works well, thanks @akabekobeko !
