### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by karlhorky** [akabekobeko/npm-gatsby-remark-copy-relative-linked-files#22]
Hi @akabekobeko 👋 hope you are well!

Just forwarding an issue that @Josehower has been experiencing on his Windows machine:

It appears that this plugin doesn't work with Windows (maybe an issue with the slashes in the paths?)

<img width="1305" alt="Screen Shot 2021-07-15 at 11 21 47" src="https://user-images.githubusercontent.com/1935696/125763997-52cf21b8-34c3-4372-b391-073106036bdd.png">

**Comment by akabekobeko** [comment]
@karlhorky 
We have not confirmed the operation on Windows. But I want to support it, so I will investigate.

It may take some time.

**Comment by akabekobeko** [comment]
Tested on Windows with GitHub Actions failed. Expected to be due to path character processing.

- [fix: Fixed incorrect directory name on GitHub Actions by akabekobeko · Pull Request #26 · akabekobeko/npm-gatsby-remark-copy-relative-linked-files](https://github.com/akabekobeko/npm-gatsby-remark-copy-relative-linked-files/pull/26/checks?check_run_id=3181095070)

**Comment by akabekobeko** [comment]
@karlhorky 
Fixed to pass automated tests on Windows. It was released as v1.4.0, so please check it.

**Comment by karlhorky** [comment]
Nice, thanks!

@Josehower can you please take a look?

**Comment by akabekobeko** [comment]
I don't have a Windows environment at hand, so I've confirmed that the unit test succeeds in the VM environment of GitHub Actions.

Please let me know if the problem reappears. Add cases that meet the conditions to the unit test.

**Comment by Josehower** [comment]
Hey! thank you so much

i can confirm now the pluggin is working as expected.

really appreciate your time and effort solving this issue.

Have a nice one!!!

![image](https://user-images.githubusercontent.com/61600906/128942205-64b0ec24-22fd-4fc6-b26c-f2aec7a7ac85.png)

**Comment by karlhorky** [comment]
Great, thanks for checking José! Closing :)
