### ISSUE TITLE
Copying videos, audio files, and other content referenced from HTML in Markdown?

### ISSUE THREAD

**Issue by karlhorky** [akabekobeko/npm-gatsby-remark-copy-relative-linked-files#7]
Hi there, first of all, thanks so much for this plugin! It's so much nicer to have the full path to the file.

I am using this with some video files embedded like this:

```html
<video src="003-resize-codesandbox-console.mp4" />
```

Would it be possible to gather these file paths and copy them as well?

Also, maybe alternative syntaxes (and audio? and maybe other types of files?):

```html
<video controls="controls">
  <source type="video/mp4" src="filename.mp4"></source>
  <source type="video/mp4" src="filename.webm"></source>
</video>

<audio controls="controls">
  <source type="audio/mp3" src="filename.mp3"></source>
</audio>
```

**Comment by akabekobeko** [comment]
@karlhorky 

Currently, only those that are linked as Markdown are copied.

However, if you can use remark to handle `audio` and` video` tags, you may want to target them as well. In that case, you should also consider `<img>` written in HTML.

Think about the policy.

**Comment by akabekobeko** [comment]
If it corresponds, it seems to be an element containing the `src` attribute. e.g. `<img>`, `<video>`, `<audio>`

**Comment by akabekobeko** [comment]
It seems better to support `<a>` within own site.

**Comment by karlhorky** [comment]
> However, if you can use remark to handle `audio` and` video` tags, you may want to target them as well

@akabekobeko Ok, I took a look at parsing the HTML / JSX and came up with this solution, which I have tested to work:

https://github.com/akabekobeko/npm-gatsby-remark-copy-relative-linked-files/pull/8

What are your thoughts? If you're happy with this direction, I can add whatever is needed to get this accepted.
